### ISSUE TITLE
Create a release tag

### ISSUE THREAD

**Issue by HeikoBoettger** [windyroad/JUnit-Schema#4]
Hi,

is it possible for you to create a release tag for the schema and adding a version number to the filename or the schema itself.

Best Regards
Heiko

**Comment by torarnv** [comment]
Since this is a schema for Apache Ant's JUnit output it would make sense to base the tags on the Apache Ant version used as a basis for the schema.

**Comment by tompahoward** [comment]
I’m not sure it would make sense to create a new release for every Ant release, especially since most people using this schema aren’t using Ant at all
