### ISSUE TITLE
Updating README.md

### ISSUE THREAD

**Issue by gdemecki** [windyroad/JUnit-Schema#5]
Hi there,

Two days ago I've found your repository on the internet and was disappointed that your work is not a part of the JUnit project :) So I created a new JUnit issue ([1387](https://github.com/junit-team/junit4/issues/1387)). But I was surprised when @kcooney told me that report generation is totally out of the JUnit.

XML report generation itself comes from the Ant JUnit task/ Maven surefire plugin. I guess it would be useful to include this information in your project's `README.md`. Also it might be valuable to have a link to the official Schema from the maven-surefire-plugin which is available [here](https://github.com/apache/maven-surefire/blob/master/maven-surefire-plugin/src/site/resources/xsd/surefire-test-report.xsd).

Also repository name itself is a bit misleading, because as you know, there is nothing like JUnit-Schema to be honest. Shouldn't this project be titled something like `ant-junit-schema`?  (but then of course some links on the internet would then become broken).

What do you think?

Kind regards,
Greg

**Comment by torarnv** [comment]
This can be closed, the README states that this is the XSD for Apache Ant's JUnit output.
